import {
  Home,
  Car,
  Wallet,
  GraduationCap,
  Leaf,
  Hammer,
  Building2,
  TrendingUp,
  Wrench,
  Factory,
  CreditCard,
  Truck,
  Sparkles,
  Briefcase,
  type LucideIcon,
} from 'lucide-react';

export interface LoanProduct {
  icon: LucideIcon;
  title: string;
  titleKey: string;
  description: string;
  descKey: string;
  amount: string;
  rate: string;
  duration: string;
  color: string;
  bgColor: string;
  features?: string[];
  featuresKey?: string;
}

export const getIndividualLoans = (t: any): LoanProduct[] => [
  {
    icon: Wallet,
    title: t.individualLoans.personalLoan,
    titleKey: 'personalLoan',
    description: t.individualLoans.personalLoanDesc,
    descKey: 'personalLoanDesc',
    amount: '€1,000 - €75,000',
    rate: '0.10% - 7%',
    duration: `12 - 84 ${t.common.months}`,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-950/20',
  },
  {
    icon: Home,
    title: t.individualLoans.mortgageLoan,
    titleKey: 'mortgageLoan',
    description: t.individualLoans.mortgageLoanDesc,
    descKey: 'mortgageLoanDesc',
    amount: '€50,000 - €500,000',
    rate: '2.5% - 4.5%',
    duration: `15 - 30 ${t.common.years}`,
    color: 'text-green-600',
    bgColor: 'bg-green-50 dark:bg-green-950/20',
  },
  {
    icon: Car,
    title: t.individualLoans.autoLoan,
    titleKey: 'autoLoan',
    description: t.individualLoans.autoLoanDesc,
    descKey: 'autoLoanDesc',
    amount: '€5,000 - €75,000',
    rate: '1.9% - 5.5%',
    duration: `24 - 84 ${t.common.months}`,
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-950/20',
  },
  {
    icon: GraduationCap,
    title: t.individualLoans.studentLoan,
    titleKey: 'studentLoan',
    description: t.individualLoans.studentLoanDesc,
    descKey: 'studentLoanDesc',
    amount: '€1,000 - €50,000',
    rate: '0.9% - 3.5%',
    duration: `24 - 120 ${t.common.months}`,
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-950/20',
  },
  {
    icon: Leaf,
    title: t.individualLoans.greenLoan,
    titleKey: 'greenLoan',
    description: t.individualLoans.greenLoanDesc,
    descKey: 'greenLoanDesc',
    amount: '€3,000 - €75,000',
    rate: '0.5% - 4.0%',
    duration: `12 - 180 ${t.common.months}`,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/20',
  },
  {
    icon: Hammer,
    title: t.individualLoans.renovationLoan,
    titleKey: 'renovationLoan',
    description: t.individualLoans.renovationLoanDesc,
    descKey: 'renovationLoanDesc',
    amount: '€1,500 - €75,000',
    rate: '2.5% - 6.9%',
    duration: `12 - 120 ${t.common.months}`,
    color: 'text-pink-600',
    bgColor: 'bg-pink-50 dark:bg-pink-950/20',
  },
  {
    icon: Sparkles,
    title: t.individualLoans.miscellaneousCredit,
    titleKey: 'miscellaneousCredit',
    description: t.individualLoans.miscellaneousCreditDesc,
    descKey: 'miscellaneousCreditDesc',
    amount: '€500 - €50,000',
    rate: '2.9% - 8.9%',
    duration: `6 - 96 ${t.common.months}`,
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 dark:bg-amber-950/20',
  },
];

export const getBusinessLoans = (t: any): LoanProduct[] => [
  {
    icon: Building2,
    title: t.businessLoans.businessLoan,
    titleKey: 'businessLoan',
    description: t.businessLoans.businessLoanDesc,
    descKey: 'businessLoanDesc',
    amount: '€10,000 - €500,000',
    rate: '3.5% - 8.5%',
    duration: `12 - 84 ${t.common.months}`,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 dark:bg-blue-950/20',
    featuresKey: 'businessLoanFeatures',
  },
  {
    icon: TrendingUp,
    title: t.businessLoans.cashFlowCredit,
    titleKey: 'cashFlowCredit',
    description: t.businessLoans.cashFlowCreditDesc,
    descKey: 'cashFlowCreditDesc',
    amount: '€5,000 - €150,000',
    rate: '4.0% - 9.0%',
    duration: `3 - 36 ${t.common.months}`,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/20',
    featuresKey: 'cashFlowCreditFeatures',
  },
  {
    icon: Wrench,
    title: t.businessLoans.equipmentFinancing,
    titleKey: 'equipmentFinancing',
    description: t.businessLoans.equipmentFinancingDesc,
    descKey: 'equipmentFinancingDesc',
    amount: '€20,000 - €300,000',
    rate: '3.9% - 7.5%',
    duration: `24 - 60 ${t.common.months}`,
    color: 'text-orange-600',
    bgColor: 'bg-orange-50 dark:bg-orange-950/20',
    featuresKey: 'equipmentFinancingFeatures',
  },
  {
    icon: Factory,
    title: t.businessLoans.commercialProperty,
    titleKey: 'commercialProperty',
    description: t.businessLoans.commercialPropertyDesc,
    descKey: 'commercialPropertyDesc',
    amount: '€50,000 - €2,000,000',
    rate: '2.9% - 5.5%',
    duration: `5 - 25 ${t.common.years}`,
    color: 'text-purple-600',
    bgColor: 'bg-purple-50 dark:bg-purple-950/20',
    featuresKey: 'commercialPropertyFeatures',
  },
  {
    icon: CreditCard,
    title: t.businessLoans.lineOfCredit,
    titleKey: 'lineOfCredit',
    description: t.businessLoans.lineOfCreditDesc,
    descKey: 'lineOfCreditDesc',
    amount: '€5,000 - €100,000',
    rate: '5.0% - 9.5%',
    duration: t.businessLoans.lineOfCreditDuration,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50 dark:bg-cyan-950/20',
    featuresKey: 'lineOfCreditFeatures',
  },
  {
    icon: Truck,
    title: t.businessLoans.vehicleFleet,
    titleKey: 'vehicleFleet',
    description: t.businessLoans.vehicleFleetDesc,
    descKey: 'vehicleFleetDesc',
    amount: '€15,000 - €250,000',
    rate: '3.2% - 6.8%',
    duration: `24 - 60 ${t.common.months}`,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 dark:bg-indigo-950/20',
    featuresKey: 'vehicleFleetFeatures',
  },
  {
    icon: Briefcase,
    title: t.businessLoans.smeLoan,
    titleKey: 'smeLoan',
    description: t.businessLoans.smeLoanDesc,
    descKey: 'smeLoanDesc',
    amount: '€25,000 - €1,000,000',
    rate: '2.9% - 7.5%',
    duration: `12 - 120 ${t.common.months}`,
    color: 'text-rose-600',
    bgColor: 'bg-rose-50 dark:bg-rose-950/20',
    featuresKey: 'smeLoanFeatures',
  },
];
